runtime: python37
service: default
entrypoint: gunicorn --chdir app --bind 0.0.0.0:8082 wsgi:app

env_variables:
  GCS_MODEL_BUCKET: wordsum-models
  GCS_MODEL_PATH: GoogleNews-vectors-negative300-first100K.bin

instance_class: F4_HIGHMEM