version: '3'
services:
  web:
    build: .
    environment:
      FLASK_PORT: 8000
      FLASK_DEBUG: "true"
    ports:
      - 8000:8000
    volumes:
      - ./app:/usr/src/wordsum/dev/app
    command: python /usr/src/wordsum/dev/app/main.py
