version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      FLASK_PORT: 8082
      FLASK_DEBUG: "true"
      ENVIRONMENT: "test"
      LOCAL_MODEL_PATH: "/usr/src/wordsum/dev/models/GoogleNews-vectors-negative300.bin.gz"
    ports:
      - 8082:8082
    volumes:
      - ./app:/usr/src/wordsum/dev/app
      - ./models:/usr/src/wordsum/dev/models
    command: python /usr/src/wordsum/dev/app/main.py
